#!/bin/bash

mount /dev/$diskp2 /mnt
cd /mnt

btrfs subvolume create ./@
btrfs subvolume create ./@home

cd
umount /mnt -R

mount -o rw,noatime,compress=zstd:3,ssd,ssd_spread,discard=async,space_cache=v2,subvol=/@ /dev/$diskp2 /mnt
mount -o rw,noatime,compress=zstd:3,ssd,ssd_spread,discard=async,space_cache=v2,subvol=/@home /dev/$diskp2 /m>
mount | grep /mnt

mkdir /mnt/boot
mount /dev/$diskp1 /mnt/boot
