#!/bin/bash

ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
hwclock --systohc

# sudo nano /etc/locale.gen

# uncoment ru_RU.UTF-8 UTF-8 and en_US.UTF-8 UTF-8


sudo touch /etc/locale.conf

sudo echo "LANG=en_US.UTF-8" >> /etc/locale.conf
# sudo echo "" >> /etc/locale.conf

locale-gen

sudo touch /etc/vconsole.conf

sudo echo "KEYMAP=ru" >> /etc/vconsole.conf
sudo echo "FONT=cyr-sun16" >> /etc/vconsole.conf
# sudo echo "" >> /etc/vconsole.conf

sudo touch /etc/hostname

sudo echo "assaytean" >> /etc/hostname
# sudo echo "" >> /etc/hostname

sudo touch /etc/hosts

sudo echo "127.0.0.1 localhost" >> /etc/hosts
sudo echo "::1 localhost" >> /etc/hosts
sudo echo "127.0.1.1 assaytean" >> /etc/hosts
# sudo echo "" >> /etc/hosts
